import {useEffect,useRef,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {api,configured,getPackage,getTopUp,purchase,purchaseTopUp,restore,supabase} from './lib';
import {adsEnabled,maybeShowPracticeAd,showAdPrivacyOptions} from './ads';
import type {Assignment,Course,Usage} from './commerce';
import UsagePanel from './UsagePanel';
import StudyWorkspace from './StudyWorkspace';
import SchoolPanel from './SchoolPanel';

export default function App(){
  const [session,setSession]=useState<Session|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState('');
  const [courses,setCourses]=useState<Course[]>([]),[course,setCourse]=useState<Course|null>(null),[newCourse,setNewCourse]=useState(''),[usage,setUsage]=useState<Usage|null>(null);
  const [page,setPage]=useState<'library'|'study'|'paywall'|'school'>('library'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[price,setPrice]=useState(''),[topUpPrice,setTopUpPrice]=useState('');
  const [assignment,setAssignment]=useState<Assignment|undefined>(),[resumeId,setResumeId]=useState<string|undefined>();
  const latest=useRef({userId:session?.user.id,page}); latest.current={userId:session?.user.id,page};
  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>data.subscription.unsubscribe();},[]);
  useEffect(()=>{setUsage(null);setCourse(null);setAssignment(undefined);setPage('library');if(session)void run(async()=>{await loadCourses();await refreshUsage();});else setCourses([]);},[session?.user.id]);
  async function run(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();}catch(e){setMessage(e instanceof Error?e.message:'Please retry.');}finally{setBusy(false);}}
  async function loadCourses(){const {data,error}=await supabase.from('courses').select('id,name,subject_type,archived_at').order('created_at',{ascending:false});if(error)throw error;setCourses(data||[]);}
  async function refreshUsage(){const result=await api<Usage>('/api/billing/usage',{});if(latest.current.userId===session?.user.id)setUsage(result);}
  function openCourse(selected:Course,a?:Assignment,resume?:string){setCourse(selected);setAssignment(a);setResumeId(resume);setPage('study');}
  async function createCourse(){const name=newCourse.trim();if(!name)throw new Error('Enter a course name.');const result=await api<{id:string}>('/api/courses/create',{name,subjectType:'law'});setNewCourse('');await loadCourses();await refreshUsage();openCourse({id:result.id,name,subject_type:'law'});}
  async function paywall(){setPage('paywall');setPrice('');setTopUpPrice('');if(!session)return;const results=await Promise.allSettled([getPackage(session.user.id),getTopUp(session.user.id)]);if(results[0].status==='fulfilled')setPrice(results[0].value.product.priceString);if(results[1].status==='fulfilled')setTopUpPrice(results[1].value.product.priceString);if(results.every(r=>r.status==='rejected'))setMessage('Purchases are available in the configured Android app. Your server allowance remains visible here.');}
  function finished(attemptId:string){setPage('library');if(!session)return;const uid=session.user.id;const key=`studymate:reviewed:${uid}:${attemptId}`;if(localStorage.getItem(key))return;localStorage.setItem(key,'true');void maybeShowPracticeAd(uid,()=>latest.current.userId===uid&&latest.current.page==='library');}
  async function signOut(){const uid=session?.user.id;for(const key of Object.keys(localStorage))if(uid&&key.startsWith('studymate:')&&key.includes(uid))localStorage.removeItem(key);await supabase.auth.signOut();}
  if(!configured)return <main className="shell"><h1>StudyMate setup needed</h1><p>Add the public Supabase configuration and backend URL to mobile/.env.</p></main>;
  return <main className="shell"><header><strong>StudyMate<span className="mark">●</span></strong><span className="eyebrow">Your material. Your momentum.</span></header>{message&&<div className="notice" role="status">{message}<button aria-label="Dismiss message" onClick={()=>setMessage('')}>×</button></div>}
    {!session?<section className="card auth"><h1>Study for the questions that count.</h1><p>Sign in with your existing StudyMate account.</p><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy} onClick={()=>void run(async()=>{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setPassword('');})}>Sign in</button></section>:<>
    <nav><button onClick={()=>setPage('library')}>Courses</button><button disabled={!course} onClick={()=>setPage('study')}>Study</button><button onClick={()=>void run(paywall)}>Pro & credits</button><button onClick={()=>setPage('school')}>Schools</button><button onClick={()=>void run(signOut)}>Sign out</button>{adsEnabled&&<button onClick={()=>void run(showAdPrivacyOptions)}>Ad privacy</button>}</nav>
    <UsagePanel usage={usage} onRefresh={()=>void run(refreshUsage)}/>
    {page==='library'&&<><div className="hero"><span className="step">CHOOSE</span><h1>One course at a time.</h1><p>Pick up your saved work or start with your own notes.</p></div><section className="card"><h2>Your courses</h2>{courses.length?courses.map(c=><div key={c.id} className="question"><button className="course" onClick={()=>openCourse(c)}>{c.name}{c.archived_at?' · Archived':' · Continue →'}</button><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{await api('/api/courses/archive',{courseId:c.id,archived:!c.archived_at});await loadCourses();await refreshUsage();})}>{c.archived_at?'Reactivate':'Archive'}</button></div>):<p>No courses yet.</p>}<p className="hint">Archiving frees an active course slot and keeps saved work and reports. Existing courses are preserved even when your current plan has a lower cap.</p></section><section className="card"><h2>New course</h2><label>Course name<input value={newCourse} onChange={e=>setNewCourse(e.target.value)} maxLength={150}/></label><button disabled={busy} onClick={()=>void run(createCourse)}>Create course</button></section></>}
    {page==='study'&&course&&<StudyWorkspace key={`${session.user.id}:${course.id}:${assignment?.id||'personal'}`} course={course} userId={session.user.id} assignment={assignment} resumeId={resumeId} onUsage={()=>void refreshUsage().catch(e=>setMessage(e.message))} onFinished={finished}/>}
    {page==='school'&&<SchoolPanel userId={session.user.id} courses={courses} onAssignment={openCourse}/>}
    {page==='paywall'&&<><div className="hero"><h1>Make room for more study.</h1><p>Saved work stays yours when your allowance runs out.</p></div><section className="card"><h2>Pro · {price||'Monthly subscription'}</h2><p>5 active courses, 30 guided sessions per calendar month, five-question practice and no ads.</p><p className="hint">A session includes material preparation, Plain and Story explanations of one topic, a practice set, saved feedback, one weak-area retry and a revision report. Generated steps are saved; a new topic needs a new session.</p><button disabled={busy||!price} onClick={()=>void run(async()=>{await purchase(session.user.id);await refreshUsage();setMessage('Purchase received. Your allowance above shows the server-verified access.');})}>Subscribe monthly</button><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{await restore(session.user.id);await refreshUsage();setMessage('Store restore checked. Your current server allowance is shown above.');})}>Restore purchases</button><p className="hint">The store shows localized price and terms before confirmation.</p></section><section className="card"><h2>10 extra sessions · {topUpPrice||'Top-up'}</h2><p>Use after your monthly allowance. Includes up to five questions per session. Credits do not add course slots or remove Free ads, and do not expire. Refunded purchases are reversed in the credit ledger.</p><button disabled={busy||!topUpPrice||!usage||usage.remaining>0} onClick={()=>void run(async()=>{await purchaseTopUp(session.user.id);await refreshUsage();setMessage('Purchase received. Credits appear after server verification; use Refresh allowance if the webhook is still processing.');})}>Buy 10-session top-up</button></section></>}
    </>}
  </main>;
}
