import { useEffect,useState } from 'react';
import { api } from './lib';
import type { Assignment,Course,SchoolDashboard } from './commerce';
export default function SchoolPanel({userId,courses,onAssignment}:{userId:string;courses:Course[];onAssignment:(course:Course,assignment:Assignment,resumeId?:string)=>void}){
  const [schools,setSchools]=useState<Array<{school_id:string;role:string;schools:{id:string;name:string}}>>([]),[canCreate,setCanCreate]=useState(false),[dashboard,setDashboard]=useState<SchoolDashboard|null>(null);
  const [name,setName]=useState(''),[code,setCode]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('student'),[cls,setClass]=useState(''),[teacher,setTeacher]=useState(''),[className,setClassName]=useState(''),[title,setTitle]=useState(''),[topic,setTopic]=useState(''),[minutes,setMinutes]=useState(20),[courseId,setCourseId]=useState(''),[message,setMessage]=useState(''),[invite,setInvite]=useState(''),[busy,setBusy]=useState(false);
  async function load(){const r=await api<{memberships:typeof schools;canCreate:boolean}>('/api/schools',{action:'list'});setSchools(r.memberships);setCanCreate(r.canCreate);}
  async function open(id:string){setDashboard(await api<SchoolDashboard>('/api/schools',{action:'dashboard',schoolId:id}));}
  async function run(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();await load();}catch(e){setMessage(e instanceof Error?e.message:'Please retry.');}finally{setBusy(false);}}
  useEffect(()=>{void run(load);},[userId]);
  async function mutate(body:object){if(!dashboard)return;await api('/api/schools',{...body,schoolId:dashboard.school.id});await open(dashboard.school.id);}
  function exportRecords(){if(!dashboard)return;const blob=new Blob([JSON.stringify({school:dashboard.school.name,assignments:dashboard.assignments,members:dashboard.members,activity:dashboard.activity},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='studymate-school-activity.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <><div className="hero"><h1>Schools</h1><p>Assignments, visible study time and practice outcomes.</p></div>{message&&<p className="notice" role="status">{message}</p>}
    <section className="card"><h2>Your schools</h2>{schools.map(s=><button key={s.school_id} onClick={()=>void run(()=>open(s.school_id))}>{s.schools.name} · {s.role}</button>)}{!schools.length&&<p>No school membership yet.</p>}<label>Invitation code<input value={code} onChange={e=>setCode(e.target.value)} autoComplete="off"/></label><button disabled={busy||!code} onClick={()=>void run(async()=>{const r=await api<{schoolId:string}>('/api/schools',{action:'join',code});setCode('');await open(r.schoolId);})}>Join your school</button>{canCreate&&<><h3>Create approved pilot</h3><p>30 days · up to 25 seats · 300 pooled sessions/month · 30 per person. A quote is needed to continue after the pilot.</p><label>School name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><button disabled={busy||name.trim().length<2} onClick={()=>void run(async()=>{const r=await api<{schoolId:string}>('/api/schools',{action:'create',name});await open(r.schoolId);})}>Create 30-day pilot</button></>}</section>
    {dashboard&&<><section className="card"><h2>{dashboard.school.name}</h2><p>Your role: {dashboard.role}. Access until {new Date(dashboard.school.expires_at).toLocaleDateString()}.</p><p>{dashboard.members.filter(m=>m.active).length}/{dashboard.school.seat_limit} seats visible · {dashboard.school.monthly_pool} pooled monthly sessions</p><button disabled={busy} onClick={()=>void run(()=>open(dashboard.school.id))}>Refresh school</button></section>
    {dashboard.role!=='student'&&<section className="card"><h2>Class management</h2>{dashboard.role==='admin'&&<><label>New class name<input value={className} onChange={e=>setClassName(e.target.value)}/></label><label>Teacher<select value={teacher} onChange={e=>setTeacher(e.target.value)}><option value="">Choose teacher</option>{dashboard.members.filter(m=>m.active&&['teacher','admin'].includes(m.role)).map(m=><option key={m.user_id} value={m.user_id}>{m.display_name}</option>)}</select></label><button disabled={busy||!teacher||!className} onClick={()=>void run(()=>mutate({action:'class',name:className,teacherId:teacher}))}>Create class</button></>}
      <label>Class<select value={cls} onChange={e=>setClass(e.target.value)}><option value="">Choose class</option>{dashboard.classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><h3>Invite a member</h3><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{dashboard.role==='admin'&&<label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="student">Student</option><option value="teacher">Teacher</option></select></label>}<button disabled={busy||!email||role==='student'&&!cls} onClick={()=>void run(async()=>{const r=await api<{code:string}>('/api/schools',{action:'invite',schoolId:dashboard.school.id,email,role:dashboard.role==='teacher'?'student':role,classId:cls||undefined});setInvite(r.code);})}>Create invitation</button>{invite&&<label>Share this code with the invited email holder<textarea readOnly value={invite}/><span className="hint">Expires in seven days. StudyMate has not sent an email.</span></label>}
      <h3>Assign study</h3><label>Assignment title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={150}/></label><label>Topic<input value={topic} onChange={e=>setTopic(e.target.value)} maxLength={300}/></label><label>Active minutes<input type="number" min={1} max={120} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><button disabled={busy||!cls||!title||!topic} onClick={()=>void run(()=>mutate({action:'assignment',classId:cls,title,topic,targetMinutes:minutes}))}>Assign to class</button></section>}
    <section className="card"><h2>Assignments</h2>{dashboard.role==='student'&&<label>Your own course<select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Choose course with this material</option>{courses.filter(c=>!c.archived_at).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{dashboard.assignments.length?dashboard.assignments.map(a=>{const progress=dashboard.activity.find(r=>r.assignment_id===a.id&&r.user_id===userId);return <article className="question" key={a.id}><h3>{a.title}</h3><p>{a.topic} · {a.target_minutes} active minutes</p>{progress&&<p>{progress.state} · {Math.floor(progress.active_seconds/60)} active minutes · {progress.practice?`${progress.practice.percentage}% practice score`:'Practice not submitted'}</p>}{dashboard.role==='student'&&<button disabled={!courseId||progress?.state==='completed'} onClick={()=>{const selected=courses.find(c=>c.id===courseId);if(selected)onAssignment(selected,a,progress?.session_id);}}>{progress?'Resume assignment':'Begin assignment'}</button>}</article>;}):<p>No assignments yet.</p>}</section>
    <section className="card"><h2>Activity records</h2><p>Only assigned-session activity is shared. Active time does not prove reading or understanding. Activity older than 90 days is removed when this dashboard loads.</p>{dashboard.activity.map(r=><p key={r.id}>{dashboard.members.find(m=>m.user_id===r.user_id)?.display_name||'Student'} · {dashboard.assignments.find(a=>a.id===r.assignment_id)?.title} · {Math.floor(r.active_seconds/60)} min · {r.state} · {r.practice?`${r.practice.percentage}%`:'No submitted practice'}{r.pause_reason?` · Pause: ${r.pause_reason}`:''}</p>)}<button onClick={exportRecords}>Export visible records</button><button className="secondary" onClick={()=>{if(window.confirm('Delete your school activity records? Your personal courses remain.'))void run(()=>mutate({action:'delete-own-records'}));}}>Delete my school records</button></section>
    {dashboard.role==='admin'&&<section className="card"><h2>Seats and pilot controls</h2>{dashboard.members.filter(m=>m.active&&m.user_id!==dashboard.school.owner_id).map(m=><p key={m.user_id}>{m.display_name} · {m.role}<button className="secondary" onClick={()=>void run(()=>mutate({action:'member',userId:m.user_id,active:false}))}>Remove seat</button></p>)}{dashboard.school.owner_id===userId&&<button className="secondary" onClick={()=>{const confirm=window.prompt('Type the school name to delete its assignments, memberships and tracking records. Personal courses remain.');if(confirm===dashboard.school.name)void run(async()=>{await api('/api/schools',{action:'delete-school',schoolId:dashboard.school.id,confirmationName:confirm});setDashboard(null);});}}>Delete school pilot</button>}</section>}</>}
  </>;
}
