import { useEffect, useRef, useState } from 'react';
import { api, shareRevisionPdf } from './lib';
import StudyTimer from './StudyTimer';
import type { Assignment, Course, Feedback, Quiz, StudySession } from './commerce';
type Result={session:StudySession;operations:Array<{operation:string;result:Record<string,unknown>}>};
export default function StudyWorkspace({course,userId,assignment,resumeId,onUsage,onFinished}:{course:Course;userId:string;assignment?:Assignment;resumeId?:string;onUsage:()=>void;onFinished:(attemptId:string)=>void}) {
  const [study,setStudy]=useState<StudySession|null>(null),[topic,setTopic]=useState(assignment?.topic||''),[mode,setMode]=useState<'plain'|'story'>('plain');
  const [explanation,setExplanation]=useState(''),[citations,setCitations]=useState<Array<string|{title?:string;quote?:string}>>([]),[quiz,setQuiz]=useState<Quiz|null>(null),[answers,setAnswers]=useState<Record<string,string>>({}),[feedback,setFeedback]=useState<Feedback|null>(null),[retry,setRetry]=useState(false);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const sessionRef=useRef<string|null>(null);
  const storageKey=`studymate:session:${userId}:${course.id}:${assignment?.id||'personal'}`;
  async function run(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();}catch(e){setMessage(e instanceof Error?e.message:'Please retry.');}finally{if(sessionRef.current){try{const current=await api<Result>('/api/study/session',{resumeId:sessionRef.current});setStudy(current.session);}catch{/* Keep the visible error and saved session for a later retry. */}}setBusy(false);onUsage();}}
  function applySaved(result:Result){
    sessionRef.current=result.session.id;setStudy(result.session);localStorage.setItem(storageKey,result.session.id);setTopic(result.session.topic||assignment?.topic||'');
    const explained=result.operations.find(o=>o.operation===`explanation_${mode}`)?.result;
    if(explained){setExplanation(explained.explanation as string);setCitations(explained.citations as typeof citations||[]);}
    const q=result.operations.find(o=>o.operation==='retry_quiz')||result.operations.find(o=>o.operation==='quiz');
    if(q){setQuiz(q.result as unknown as Quiz);setRetry(q.operation==='retry_quiz');}
    const f=result.operations.find(o=>o.operation===(q?.operation==='retry_quiz'?'retry_feedback':'feedback'));
    setFeedback(f ? f.result as unknown as Feedback : null);
    try{setAnswers(JSON.parse(localStorage.getItem(`studymate:draft:${userId}:${result.session.id}`)||'{}'));}catch{setAnswers({});}
  }
  useEffect(()=>{const id=resumeId||localStorage.getItem(storageKey);if(id)void run(async()=>applySaved(await api<Result>('/api/study/session',{resumeId:id})));},[storageKey,resumeId]);
  useEffect(()=>{if(study)localStorage.setItem(`studymate:draft:${userId}:${study.id}`,JSON.stringify(answers));},[answers,study?.id,userId]);
  async function ensureSession(){
    if(study)return study;
    let key=localStorage.getItem(storageKey+':request');if(!key){key=crypto.randomUUID();localStorage.setItem(storageKey+':request',key);}
    const result=await api<Result>('/api/study/session',{courseId:course.id,topic:topic.trim(),requestKey:key,assignmentId:assignment?.id});applySaved(result);return result.session;
  }
  function newSession(){sessionRef.current=null;setStudy(null);setExplanation('');setQuiz(null);setFeedback(null);setAnswers({});setRetry(false);localStorage.removeItem(storageKey);localStorage.removeItem(storageKey+':request');setMessage('The next successful session uses one allowance. Saved work remains in your course report.');}
  async function prepare(){const s=await ensureSession();await api('/api/agents/wiki',{courseId:course.id,studySessionId:s.id});setMessage('Material prepared. Enter a topic and learn.');}
  async function learn(){if(!topic.trim())throw new Error('Enter a topic.');const s=await ensureSession();const result=await api<{explanation:string;citations:typeof citations}>('/api/agents/explainer',{courseId:course.id,studySessionId:s.id,topic:topic.trim(),mode});setStudy({...s,topic:topic.trim()});setExplanation(result.explanation);setCitations(result.citations||[]);}
  async function practise(count:number){const s=await ensureSession();const q=await api<Quiz>('/api/agents/quiz',{courseId:course.id,studySessionId:s.id,quizType:'mixed',questionCount:count});setQuiz(q);setFeedback(null);setAnswers({});setRetry(false);}
  async function submit(){if(!study||!quiz)return;const f=await api<Feedback>('/api/study/submit',{courseId:course.id,studySessionId:study.id,retry,answers:quiz.questions.map(q=>({questionId:q.id,answer:answers[q.id]||''}))});setFeedback(f);}
  async function retryWeak(){if(!study)return;setQuiz(await api<Quiz>('/api/study/retry',{courseId:course.id,studySessionId:study.id}));setAnswers({});setFeedback(null);setRetry(true);}
  return <><div className="hero"><span className="step">STUDY</span><h1>{course.name}</h1><p>{assignment?assignment.title:'Upload → learn → practise → revision'}</p></div>{message&&<p className="notice" role="status">{message}</p>}
    {study&&assignment&&<StudyTimer key={study.id} sessionId={study.id} targetMinutes={assignment.target_minutes}/>}
    {assignment&&study&&(study.status==='released'||Date.parse(study.expires_at)<Date.now())&&<button onClick={newSession}>Restart expired assignment session</button>}{assignment&&!study&&<section className="card"><p>Begin this assignment in your own course. Your active timer and submitted practice result are shared with your class teacher.</p><button disabled={busy} onClick={()=>void run(async()=>{await ensureSession();})}>Begin assigned session</button></section>}
    <section className="card"><h2>Add material</h2><label>Choose text PDF or .txt<input type="file" disabled={busy||!!course.archived_at} accept=".pdf,.txt" onChange={e=>void run(async()=>{const f=e.target.files?.[0];if(!f)return;if(f.size>10*1024*1024)throw new Error('Use a file smaller than 10 MB.');const form=new FormData();form.set('courseId',course.id);form.set('file',f);await api('/api/upload',form);if(!assignment)newSession();setMessage('Upload accepted. Wait for processing, then prepare learning.');})}/></label><button disabled={busy||!!course.archived_at} onClick={()=>void run(prepare)}>Prepare learning</button></section>
    <section className="card"><h2>Understand one topic</h2><label>Topic<input value={topic} disabled={!!assignment||!!study?.topic} onChange={e=>setTopic(e.target.value)} maxLength={300}/></label><div className="segmented"><button onClick={()=>setMode('plain')}>Plain</button><button onClick={()=>setMode('story')}>Story</button></div><button disabled={busy||!!course.archived_at} onClick={()=>void run(learn)}>Explain this topic</button>{explanation&&<article className="answer"><pre>{explanation}</pre><details><summary>Sources used</summary>{citations.map((c,i)=><p key={i}>{typeof c==='string'?c:c.title||c.quote}</p>)}</details></article>}</section>
    <section className="card"><h2>Practice and saved feedback</h2><p>One set and one targeted retry are included in your session. Answers are graded against the saved questions on the server.</p><div className="actions"><button disabled={busy||!!course.archived_at} onClick={()=>void run(()=>practise(3))}>3 questions</button><button className="secondary" disabled={busy||!!course.archived_at} onClick={()=>void run(()=>practise(5))}>5 · Pro, School or top-up</button></div>{quiz&&quiz.questions.map((q,i)=><div className="question" key={q.id}><h3>{i+1}. {q.question}</h3>{q.source_material&&<p className="hint">Source: {q.source_material}</p>}{q.options?.map(o=><label key={o.label}><input type="radio" name={q.id} disabled={!!feedback} checked={answers[q.id]===o.label} onChange={()=>setAnswers(a=>({...a,[q.id]:o.label}))}/>{o.label}. {o.text}</label>)}{q.type==='essay'&&<label>Your answer<textarea disabled={!!feedback} value={answers[q.id]||''} maxLength={3000} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))}/></label>}</div>)}{quiz&&!feedback&&<button disabled={busy||quiz.questions.some(q=>!answers[q.id]?.trim())} onClick={()=>void run(submit)}>Submit practice set</button>}{feedback&&<article className="feedback"><h3>Practice score: {feedback.percentage}%</h3><pre>{feedback.feedback}</pre>{!retry&&<button disabled={busy} onClick={()=>void run(retryWeak)}>Retry weak areas · included</button>}<button disabled={busy} onClick={()=>feedback&&onFinished(feedback.attemptId)}>Finish review · return to courses</button></article>}</section>
    <section className="card"><h2>Keep your revision report</h2><p>Saved submissions and practice results are included. Opening this report uses no sessions.</p><button disabled={busy} onClick={()=>void run(()=>shareRevisionPdf(course.id))}>Download / share PDF</button>{!assignment&&<button className="secondary" onClick={newSession}>Start a new topic session</button>}</section>
  </>;
}
